CREATE USER 'CEO'@'%' IDENTIFIED BY '1234';
CREATE USER 'Admin'@'%' IDENTIFIED BY '1234';
CREATE USER 'CSO'@'%' IDENTIFIED BY '1234';
CREATE USER 'Sales'@'%' IDENTIFIED BY '1234';
CREATE USER 'CPO'@'%' IDENTIFIED BY '1234';
CREATE USER 'Purchases'@'%' IDENTIFIED BY '1234';
CREATE USER 'login'@'%' IDENTIFIED BY '1234';

